In [5]:
import torch
# random new tensor
tensor = torch.Tensor([[1, 2], [3, 4]])

# 2x3 tensor with random values
empty_tensor = torch.Tensor(2, 3)

# 2x3 tensor with random values between -1 and 1
uniform_tensor = torch.Tensor(2, 3).uniform_(-1, 1)

# 2x3 tensor with random values from a uniform distribution on the interval[0, 1]
rand_tensor = torch.rand(2,3)

# 2x3 tensor of zeros
zero_tensor = torch.zeros(2, 3)

In [6]:
tensor_dict = {"New Tensor":tensor,
              "Empty Tensor":empty_tensor,
              "Uniform (-1, 1) Tensor":uniform_tensor,
              "Random (0, 1) Tensor":rand_tensor,
              "Zero Tensor":zero_tensor}

In [7]:
for k in tensor_dict.keys():
    print(k)
    print(tensor_dict[k])
    print("\n\n")

New Tensor
tensor([[1., 2.],
        [3., 4.]])



Empty Tensor
tensor([[0.0000e+00, 8.4490e-39, 1.8754e+28],
        [8.0439e+20, 2.6540e+20, 1.2802e-11]])



Uniform (-1, 1) Tensor
tensor([[ 0.3420,  0.6253, -0.9717],
        [-0.7512, -0.7559,  0.9578]])



Random (0, 1) Tensor
tensor([[0.7080, 0.0999, 0.9699],
        [0.9103, 0.0355, 0.4161]])



Zero Tensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])





In [8]:
tensor = torch.Tensor([[1, 2], [3, 4]])

tensor[0][0] = 5
tensor

tensor([[5., 2.],
        [3., 4.]])

In [9]:
slice_tensor = torch.Tensor(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
slice_tensor[:, 0]

tensor([1., 4., 7.])

In [10]:
slice_tensor[:, -1]

tensor([3., 6., 9.])

In [11]:
slice_tensor[2, :]

tensor([7., 8., 9.])

In [12]:
slice_tensor[:2, :]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
tensor = torch.Tensor(([1, 2], [3, 4]))

tensor.type()

'torch.FloatTensor'

In [17]:
tensor.shape, tensor.size(), tensor.dim()

(torch.Size([2, 2]), torch.Size([2, 2]), 2)

In [20]:
reshape_tensor = torch.Tensor(([1, 2], [3, 4]))

reshape_tensor.view(1, 4), reshape_tensor.view(4, 1)

(tensor([[1., 2., 3., 4.]]),
 tensor([[1.],
         [2.],
         [3.],
         [4.]]))

In [22]:
import numpy as np

np_array = np.random.randn(2, 2)
to_tensor = torch.from_numpy(np_array)
to_ndarray = to_tensor.numpy()

In [23]:
np_array

array([[-0.61631724, -0.30562763],
       [ 1.8134887 ,  1.34467914]])

In [24]:
to_tensor

tensor([[-0.6163, -0.3056],
        [ 1.8135,  1.3447]], dtype=torch.float64)

In [26]:
to_ndarray

array([[-0.61631724, -0.30562763],
       [ 1.8134887 ,  1.34467914]])

In [33]:
print(tensor, "\n\n", tensor.t())

tensor([[1., 2.],
        [3., 4.]]) 

 tensor([[1., 3.],
        [2., 4.]])


In [35]:
print(tensor.permute(-1, 0)) #transpose via permute function

tensor([[1., 3.],
        [2., 4.]])


In [45]:
tensor1 = torch.randn(3, 3)
tensor2 = torch.randn(3, 3)

cross_prod = tensor1.cross(tensor2) # CROSS PRODUCT
# cross_prod = torch.cross(tensor1, tensor2)
cross_prod

tensor([[-1.2617, -0.4881,  1.9157],
        [-1.3076, -0.0956, -0.0996],
        [-0.5930, -1.2238,  0.6999]])

In [46]:
tensor1

tensor([[ 0.2362,  0.4664, -0.5713],
        [-1.0425, -0.2243,  0.3888],
        [ 1.7964, -0.1685,  1.6189]])

In [47]:
tensor2

tensor([[-0.8067, -0.7462, -0.5150],
        [ 1.0503, -2.2650, -0.8747],
        [-0.5996,  0.4745,  1.2850]])

In [48]:
matrix_prod = tensor1.mm(tensor2) # MATRIX PRODUCT
matrix_prod

tensor([[ 0.6419, -1.5038, -1.2638],
        [ 0.3724,  1.4704,  1.2326],
        [-2.5969, -0.1906,  1.3027]])

In [49]:
element_mult = tensor1.mul(tensor2) # MULTIPLICATION
element_mult

tensor([[-0.1905, -0.3480,  0.2942],
        [-1.0950,  0.5080, -0.3401],
        [-1.0771, -0.0800,  2.0804]])

In [51]:
if torch.cuda.is_available():
    tensor1 = tensor1.cuda()
    tensor2 = tensor2.cuda()
    print(tensor1 + tensor2)

tensor([[-0.5706, -0.2798, -1.0863],
        [ 0.0078, -2.4893, -0.4860],
        [ 1.1968,  0.3060,  2.9039]], device='cuda:0')
