In [1]:
import numpy as np

In [37]:
y_pred = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

#### MEAN ABSOLUTE ERROR

In [3]:
def mae(y_pred, y_true):
    total_error = 0
    for yp, yt in zip(y_pred, y_true):
        total_error += abs(yp - yt)
    print(f"Total error: {total_error}")
    mae = total_error / len(y_pred)
    print(f"Mean Absolute Error: {mae}")

In [4]:
mae(y_pred, y_true)

Total error: 2.5
Mean Absolute Error: 0.5


##### same but numpy

In [5]:
np.abs(y_pred - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_pred - y_true))

0.5

In [7]:
def mae_numpy(y_pred, y_true):
    return np.mean(np.abs(y_pred - y_true))

In [8]:
mae_numpy(y_pred, y_true)

0.5

##### Log Loss & Binary Cross Entropy

In [9]:
np.log([0])

R:\Work\Anacond\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [10]:
epsilon = 1e-15

In [11]:
np.log([epsilon])

array([-34.53877639])

In [17]:
y_pred

array([1, 1, 0, 0, 1])

In [18]:
y_pred_new = [max(i, epsilon) for i in y_pred]
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [19]:
1 - epsilon

0.999999999999999

In [20]:
y_pred_new = [min(i, 1 - epsilon) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [21]:
y_pred_new = np.array(y_pred_new)

In [22]:
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [23]:
formula1 = y_true * np.log(y_pred_new)
formula2 = (1 - y_true) * np.log(1 - y_pred_new)
-np.mean(formula1 + formula2)

17.2696280766844

In [24]:
def log_loss(y_true, y_pred):
    y_pred_new = [max(i, epsilon) for i in y_pred]
    y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

In [26]:
log_loss(y_true, y_pred)

17.2696280766844

#### Mean Squared Error

In [38]:
def mse(y_pred, y_true):
    total = 0
    for yp, yt in zip(y_pred, y_true):
        total += (yp - yt)**2
    print(f"Total Sqared Error: {total}")
    mse =  total / len(y_pred)
    print(f"Mean Squared Error: {mse}")
    return mse

In [40]:
mse(y_pred, y_true)

Total Sqared Error: 1.83
Mean Squared Error: 0.366


0.366

In [41]:
np.mean(np.square(y_true - y_pred))

0.366